# Generated by Django 4.2 on 2023-06-12 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='usrN',
            field=models.CharField(max_length=100, verbose_name='Nombre de Usuario'),
        ),
    ]
