# Generated by Django 4.2 on 2023-06-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_usuarios_usrn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='pswrdN',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='pswrdN2',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default=1, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='usrN',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre de Usuario'),
        ),
    ]
