# Generated by Django 4.2 on 2023-06-14 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_usuarios_pswrdn_remove_usuarios_pswrdn2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='password',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='pswrdN',
            field=models.CharField(default=1, max_length=15, verbose_name='Contraseña'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuarios',
            name='pswrdN2',
            field=models.CharField(default=11, max_length=15, verbose_name='Contraseña2'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='usrN',
            field=models.CharField(max_length=100, verbose_name='Nombre de Usuario'),
        ),
    ]
