# Generated by Django 4.2 on 2023-07-01 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_usuarios_last_login_remove_usuarios_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalorder',
            name='products',
        ),
        migrations.CreateModel(
            name='RentalOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.IntegerField()),
                ('rental_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.rentalorder')),
            ],
        ),
    ]
