# Generated by Django 4.2 on 2023-07-02 02:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_rentalorder_products_rentalorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalorder',
            name='create_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
