# Generated by Django 4.2 on 2023-07-03 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_rentalorder_create_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalorder',
            name='email',
            field=models.EmailField(default='default@correo.cl', max_length=254),
        ),
    ]
